name: TechExcellence
title: null
description: Taking software development to the next level
url: https://www.techexcellence.io
# baseurl : /something

include: ['_pages']

# Build settings
# theme: minima
# theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap

permalink: /:year/:month/:day/:title
# permalink: pretty

# if collections not at root level
collections_dir: content

collections:
  members:
    output: true
    # order:
    #   - jelena-cupac.md
    #   - j-cupac.md
    #   - valentina-cupac.md
  companies:
    output: true

# defaults:
#   - scope:
#       path: "_members"
#       type: "members"
#     values:
#       layout: "member"
#   - scope:
#       path: ""


sass:
  # where to search for Sass files, if the folder is called '_scss'
  # sass_dir: assets/css
  # sass_dir: _sass (default)
  sass_dir: _scss
  # Enable minification on your compiled CSS
  style: compressed
  
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap